#pragma once

/* XMM7360 RPC call IDs — ported from rpc_call_ids.py */

#define XMM_CMD_UtaMsSimOpenReq                          0x001
#define XMM_CMD_UtaMsSimApduCmdReq                       0x002
#define XMM_CMD_UtaMsSimApplicationReq                   0x004
#define XMM_CMD_UtaMsSimDecodeFcp                        0x006
#define XMM_CMD_UtaMsSimPbReadEntryReq                   0x00D
#define XMM_CMD_UtaMsSimGenPinReq                        0x00F
#define XMM_CMD_UtaMsSimModifyLockReq                    0x011
#define XMM_CMD_UtaMsSimTkProactiveCommandRsp            0x016
#define XMM_CMD_UtaMsSimTkEnvelopeCommandReq             0x017
#define XMM_CMD_UtaMsSimTkTerminalProfileReadReq         0x019
#define XMM_CMD_UtaMsSimTkRegisterHandler                0x01C
#define XMM_CMD_UtaMsSimTkDeregisterHandler              0x01D
#define XMM_CMD_UtaMsCpsSetModeReq                       0x01F
#define XMM_CMD_UtaMsCpsSetStackModeConfiguration        0x020
#define XMM_CMD_UtaMsCpsSetSimModeConfiguration          0x021
#define XMM_CMD_UtaMsCpsReadImei                         0x023
#define XMM_CMD_UtaMsCallCsInit                          0x024
#define XMM_CMD_UtaMsCbsInit                             0x025
#define XMM_CMD_UtaMsSsInit                              0x026
#define XMM_CMD_UtaMsSsSendUssdReq                       0x027
#define XMM_CMD_UtaMsSsRespondUssd                       0x028
#define XMM_CMD_UtaMsSsAbort                             0x029
#define XMM_CMD_UtaMsSmsInit                             0x030
#define XMM_CMD_UtaMsSmsSendReq                          0x031
#define XMM_CMD_UtaMsSmsSetMemoryAvailableReq            0x034
#define XMM_CMD_UtaMsSmsIncomingSmsAck                   0x036
#define XMM_CMD_UtaMsSmsSimMsgCountReq                   0x038
#define XMM_CMD_UtaMsCallPsInitialize                    0x03A
#define XMM_CMD_UtaMsCallPsObtainPdpContextId            0x03B
#define XMM_CMD_UtaMsCallPsReleasePdpContextId           0x03C
#define XMM_CMD_UtaMsCallPsDefinePrimaryReq              0x03D
#define XMM_CMD_UtaMsCallPsUndefinePrimaryReq            0x03F
#define XMM_CMD_UtaMsCallPsGetPrimaryReq                 0x041
#define XMM_CMD_UtaMsCallPsSetAuthenticationReq          0x043
#define XMM_CMD_UtaMsCallPsSetDnsReq                     0x045
#define XMM_CMD_UtaMsCallPsGetNegotiatedDnsReq           0x047
#define XMM_CMD_UtaMsCallPsGetNegIpAddrReq               0x049
#define XMM_CMD_UtaMsCallPsActivateReq                   0x04B
#define XMM_CMD_UtaMsCallPsDeactivateReq                 0x04E
#define XMM_CMD_UtaMsCallPsConnectReq                    0x051
#define XMM_CMD_UtaMsNetOpen                             0x053
#define XMM_CMD_UtaMsNetSetRadioSignalReporting          0x054
#define XMM_CMD_UtaMsNetSingleShotRadioSignalReportingReq 0x055
#define XMM_CMD_UtaMsNetAttachReq                        0x05C
#define XMM_CMD_UtaMsNetPsAttachReq                      0x05D
#define XMM_CMD_UtaMsNetPsDetachReq                      0x05E
#define XMM_CMD_UtaMsNetScanReq                          0x05F
#define XMM_CMD_UtaMsNetScanAbort                        0x060
#define XMM_CMD_UtaMsNetPowerDownReq                     0x061
#define XMM_CMD_UtaMsNetExtScanReq                       0x062
#define XMM_CMD_UtaMsNetSetFdConfigReq                   0x06E
#define XMM_CMD_UtaMsNetGetFdConfigReq                   0x071
#define XMM_CMD_UtaMsNetConfigureNetworkModeReq          0x073
#define XMM_CMD_UtaMsNetRatModeStatusReq                 0x076
#define XMM_CMD_UtaNvmRead                               0x079
#define XMM_CMD_UtaNvmWrite                              0x07A
#define XMM_CMD_UtaNvmWriteCommit                        0x07B
#define XMM_CMD_UtaSysGetInfo                            0x07C
#define XMM_CMD_UtaRPCPSConnectSetupReq                  0x07D
#define XMM_CMD_UtaRPCPsConnectToDatachannelReq          0x07E
#define XMM_CMD_UtaRPCPSConnectReleaseReq                0x07F
#define XMM_CMD_UtaMsNetDcSetVoiceDomainPreferenceConfigReq 0x080
#define XMM_CMD_UtaMsCallCsSetupVoiceCallReq             0x082
#define XMM_CMD_UtaMsCallCsReleaseCallReq                0x088
#define XMM_CMD_UtaMsCallCsAcceptCallReq                 0x08D
#define XMM_CMD_UtaMsCallCsSwapCallsReq                  0x090
#define XMM_CMD_UtaMsCallCsHoldCallReq                   0x092
#define XMM_CMD_UtaMsCallCsRetrieveCallReq               0x094
#define XMM_CMD_UtaMsCallCsSplitMptyReq                  0x096
#define XMM_CMD_UtaMsCallCsJoinCallsReq                  0x098
#define XMM_CMD_UtaMsCallCsTransferCallsReq              0x09A
#define XMM_CMD_UtaMsCallCsStartDtmfReq                  0x09C
#define XMM_CMD_UtaMsCallCsStopDtmfReq                   0x09E
#define XMM_CMD_UtaMsCallCsSetUus1Info                   0x0A6
#define XMM_CMD_UtaMsCallCsSetTtyDeviceMode              0x0A7
#define XMM_CMD_UtaMsCallCsGetTtyDeviceMode              0x0A8
#define XMM_CMD_UtaMsCallMultimediaSetupCallReq          0x0AC
#define XMM_CMD_UtaMsCallMultimediaUpdateCallReq         0x0AD
#define XMM_CMD_UtaMsCpsSetSimModeReq                    0x0B0
#define XMM_CMD_UtaMsSsCallForwardReq                    0x0B2
#define XMM_CMD_UtaMsSsCallWaitingReq                    0x0B4
#define XMM_CMD_UtaMsSsCallBarringReq                    0x0B6
#define XMM_CMD_UtaMsSsIdentificationReq                 0x0B8
#define XMM_CMD_UtaMsSmsSetSendMoreMessagesStatus        0x0BA
#define XMM_CMD_UtaMsSmsDataDownloadReq                  0x0BB
#define XMM_CMD_UtaMsSmsDataDownloadAck                  0x0BD
#define XMM_CMD_UtaMsCallPsGetNegQosReq                  0x0BE
#define XMM_CMD_UtaMsCallPsGetTftReq                     0x0C0
#define XMM_CMD_UtaMsCallPsSetPcoReq                     0x0C2
#define XMM_CMD_UtaMsCallPsGetNwPcoReq                   0x0C4
#define XMM_CMD_UtaMsCallPsNwActivateAcceptReq           0x0C7
#define XMM_CMD_UtaMsCallPsNwActivateRejectReq           0x0C9
#define XMM_CMD_UtaMsCallPsSetDataPrefReq                0x0CD
#define XMM_CMD_UtaMsCbsStartReq                         0x0CF
#define XMM_CMD_UtaMsCbsStopReq                          0x0D0
#define XMM_CMD_UtaMsCbsSetMsgFilter                     0x0D3
#define XMM_CMD_UtaMsCbsGetMsgFilter                     0x0D4
#define XMM_CMD_UtaMsCbsEtwsConfigReq                    0x0D6
#define XMM_CMD_UtaMsCbsEtwsStartReq                     0x0D8
#define XMM_CMD_UtaMsCbsEtwsStopReq                      0x0DA
#define XMM_CMD_UtaMsCpsNvmWrite                         0x0DE
#define XMM_CMD_UtaMsCpsNvmRead                          0x0DF
#define XMM_CMD_UtaMsNetConfigureRxDiversityDarp         0x0E0
#define XMM_CMD_UtaMsNetLdrGetApnParameterList           0x0E2
#define XMM_CMD_UtaMsNetTimeInfoReadReq                  0x0E3
#define XMM_CMD_UtaMsNetSetCsgConfigReq                  0x0E6
#define XMM_CMD_UtaMsNetBandStatusReq                    0x0E7
#define XMM_CMD_UtaMsNetGetExtendedRadioSignalInfoReq    0x0EC
#define XMM_CMD_UtaMsNetDetachReq                        0x0EF
#define XMM_CMD_UtaMsNetSelectGprsClassReq               0x0F1
#define XMM_CMD_UtaMsNetGetCsgConfigReq                  0x0F3
#define XMM_CMD_UtaMsNetCsServiceNotificationAccept      0x0F4
#define XMM_CMD_UtaMsNetSingleShotFdReq                  0x0F9
#define XMM_CMD_UtaMsSimPbLocationReq                    0x0FB
#define XMM_CMD_UtaMsSimPbReadGasEntryReq                0x0FD
#define XMM_CMD_UtaMsSimPbWriteEntryReq                  0x0FF
#define XMM_CMD_UtaMsSimPbGetMetaInformationReq          0x101
#define XMM_CMD_UtaMsSimPbUsimPbSelectReq                0x103
#define XMM_CMD_UtaMsSimPbGetFreeRecordsReq              0x105
#define XMM_CMD_UtaMsSimCreateReadBinaryApdu             0x10A
#define XMM_CMD_UtaMsSimCreateUpdateBinaryApdu           0x10B
#define XMM_CMD_UtaMsSimAnalyseReadResult                0x10C
#define XMM_CMD_UtaMsSimSetFdnReq                        0x10E
#define XMM_CMD_SetApScreenState                         0x110
#define XMM_CMD_UtaIoCtl                                 0x111
#define XMM_CMD_UtaIdcApMsgSetReq                        0x114
#define XMM_CMD_UtaIdcApMsgGetReq                        0x115
#define XMM_CMD_UtaIdcEnbleReq                           0x116
#define XMM_CMD_UtaIdcCwsMsgSetReq                       0x119
#define XMM_CMD_UtaIdcCwsMsgGetReq                       0x11A
#define XMM_CMD_UtaIdcSubscribeIndications               0x11C
#define XMM_CMD_UtaIdcUnsubscribeIndications             0x11D
#define XMM_CMD_UtaBootPrepareShutdownReq                0x11F
#define XMM_CMD_UtaBootShutdownReq                       0x120
#define XMM_CMD_UtaRfMaxTxPwrSet2g                       0x121
#define XMM_CMD_UtaRfMaxTxPwrSet3g                       0x122
#define XMM_CMD_UtaRfMaxTxPwrSet4g                       0x123
#define XMM_CMD_UtaFreqInfoActivateReq                   0x128
#define XMM_CMD_UtaFreqInfoGetFreqInfoReq                0x129
#define XMM_CMD_UtaFreqInfoDeactivateReq                 0x12A
#define XMM_CMD_UtaFreqInfoRegisterIndications           0x12B
#define XMM_CMD_UtaFreqInfoDeregisterIndications         0x12C
#define XMM_CMD_UtaModeSetReq                            0x12F
#define XMM_CMD_UtaNvmFlushSync                          0x130
#define XMM_CMD_UtaProdRegisterGtiCallbackFunc           0x132
#define XMM_CMD_UtaProdGtiCmdReq                         0x133
#define XMM_CMD_UtaCellTimeStampReq                      0x134
#define XMM_CMD_UtaMsSsLcsInit                           0x136
#define XMM_CMD_UtaMsSsLcsMoLocationReq                  0x137
#define XMM_CMD_UtaMsSsLcsMtlrNotificationRsp            0x139
#define XMM_CMD_UtaMsCpAssistanceDataInjectReq           0x13C
#define XMM_CMD_UtaMsCpResetAssistanceData               0x13D
#define XMM_CMD_UtaMsCpPosMeasurementReq                 0x140
#define XMM_CMD_UtaMsCpPosMeasurementAbortReq            0x142
#define XMM_CMD_UtaMsCpPosEnableMeasurementReport        0x144
#define XMM_CMD_UtaMsCpPosDisableMeasurementReport       0x145
#define XMM_CMD_UtaMsSimTkInit                           0x146
#define XMM_CMD_UtaMsSimTkExecSmsPpRsp                   0x148
#define XMM_CMD_UtaMsSimTkExecSimInitiatedCallRsp        0x14A
#define XMM_CMD_UtaMsSimTkExecSsUssdRsp                  0x14C
#define XMM_CMD_UtaMsSimTkExecDtmfRsp                    0x14E
#define XMM_CMD_UtaMsSimTkStopDtmfReq                    0x150
#define XMM_CMD_UtaMsSimTkRefreshConfirmRsp              0x152
#define XMM_CMD_UtaMsSimTkRefreshFcnRsp                  0x154
#define XMM_CMD_UtaMsSimTkControlReq                     0x155
#define XMM_CMD_UtaMsSimTkTerminalProfileDownloadReq     0x157
#define XMM_CMD_UtaMs3gpp2SmsSendReq                     0x15A
#define XMM_CMD_UtaMs3gpp2SmsSubscribeIndications        0x15C
#define XMM_CMD_UtaMs3gpp2SmsUnsubscribeIndications      0x15D
#define XMM_CMD_RpcGetRemoteVerInfo                       0x15E
#define XMM_CMD_UtaMsMetricsRegisterHandler              0x160
#define XMM_CMD_UtaMsMetricsDeregisterHandler            0x161
#define XMM_CMD_UtaMsMetricsSetOptions                   0x162
#define XMM_CMD_UtaMsMetricsTrigger                      0x163
#define XMM_CMD_UtaMsEmbmsInit                           0x164
#define XMM_CMD_UtaMsEmbmsSetServiceReq                  0x165
#define XMM_CMD_UtaMsEmbmsMbsfnAreaConfigReq             0x166
#define XMM_CMD_UtaMsEmbmsSessionConfigReq               0x167
#define XMM_CMD_UtaMsEmbmsSetInterestedTMGIListReq       0x168
#define XMM_CMD_UtaMsEmbmsSetInterestedSAIFreqReq        0x169
#define XMM_CMD_UtaImsSubscribeIndications               0x176
#define XMM_CMD_UtaImsUnsubscribeIndications             0x177
#define XMM_CMD_UtaImsGetFrameworkState                  0x178
#define XMM_CMD_UtaRtcGetDatetime                        0x179
#define XMM_CMD_UtaMsSimAnalyseSimApduResult             0x17A
#define XMM_CMD_UtaMsSimOpenChannelReq                   0x17B
#define XMM_CMD_UtaMsSimCloseChannelReq                  0x17D
#define XMM_CMD_UtaMsSimSetBdnReq                        0x17F
#define XMM_CMD_UtaMsSetSimStackMappingReq               0x181
#define XMM_CMD_UtaMsGetSimStackMappingReq               0x183
#define XMM_CMD_UtaMsNetSetRadioSignalReportingConfiguration 0x188
#define XMM_CMD_UtaPCIeEnumerationextTout                0x189
#define XMM_CMD_UtaMsSimTkSetTerminalCapabilityReq       0x18A
#define XMM_CMD_UtaMsSimTkReadTerminalCapabilityReq      0x18C
#define XMM_CMD_CsiFccLockQueryReq                       0x18E
#define XMM_CMD_CsiFccLockGenChallengeReq                0x190
#define XMM_CMD_CsiFccLockVerChallengeReq                0x192
#define XMM_CMD_UtaSensorOpenReq                         0x194
#define XMM_CMD_UtaSensorCloseExt                        0x197
#define XMM_CMD_UtaSensorStartExt                        0x198
#define XMM_CMD_UtaSensorSetAlarmParamExt                0x199
#define XMM_CMD_UtaSensorSetSchedulerParamExt            0x19A
#define XMM_CMD_CsiSioIpFilterCntrlSetReq                0x19B
#define XMM_CMD_UtaMsAccCurrentFreqInfoReq               0x19D
#define XMM_CMD_CsiTrcAtCmndReq                          0x1A0
#define XMM_CMD_UtaMsSimApduCmdExtReq                    0x1A2
#define XMM_CMD_UtaMsNetGetPlmnNameInfoReq               0x1A4
#define XMM_CMD_UtaMsNetGetCountryListReq                0x1A7
#define XMM_CMD_UtaMsNetExtConfigureNetworkModeReq       0x1A9
#define XMM_CMD_UtaMsNetExtBandStatusReq                 0x1AC
#define XMM_CMD_UtaMsCallPsAttachApnConfigReq            0x1AF
#define XMM_CMD_CsiMsCallPsInitialize                    0x1B1
#define XMM_CMD_UtaAudioEnableSource                     0x1B2
#define XMM_CMD_UtaAudioDisableSource                    0x1B3
#define XMM_CMD_UtaAudioConfigureDestinationExt          0x1B4
#define XMM_CMD_UtaAudioSetDestinationsForSource         0x1B5
#define XMM_CMD_UtaAudioSetVolumeForSource               0x1B6
#define XMM_CMD_UtaAudioSetMuteForSourceExt              0x1B7
#define XMM_CMD_UtaAudioSetVolumeForDestination          0x1B8
#define XMM_CMD_UtaAudioSetMuteForDestinationExt         0x1B9
#define XMM_CMD_UtaAudioConfigureSourceExt               0x1BA
#define XMM_CMD_UtaAudioSetDestinationsForSourceExt      0x1BB
#define XMM_CMD_UtaRPCScreenControlReq                   0x1BC
#define XMM_CMD_UtaMsCallPsReadContextStatusReq          0x1BD
#define XMM_CMD_CsiMsSimAccessGetSimStateInfoReq         0x1BF
#define XMM_CMD_CsiMsNetGetRegistrationInfoReq           0x1C1
#define XMM_CMD_CsiSioIpFilterNewCntrlSetReq             0x1C3
#define XMM_CMD_CsiMsNetLdrGetApnPlmnParameterListReq    0x1C5
#define XMM_CMD_RPCGetAPIParamChangedBitmap              0x1C8

/* Unsolicited codes referenced internally */
#define XMM_UNSOL_UtaMsNetSingleShotRadioSignalReportingRspCb 0x056
#define XMM_UNSOL_UtaMsNetRadioSignalIndCb               0x05A
#define XMM_UNSOL_UtaMsNetIsAttachAllowedIndCb           0x06C
#define XMM_UNSOL_UtaModeSetRspCb                        0x12D
#define XMM_UNSOL_CsiFccLockQueryRspCb                   0x18F
#define XMM_UNSOL_CsiFccLockGenChallengeRspCb            0x191
#define XMM_UNSOL_CsiFccLockVerChallengeRspCb            0x193
