name: Publish to AUR
on:
  push:
    tags: [ 'v*' ]
    paths: [ 'PKGBUILD' ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: xmm7360-dkms-git
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: "Update from ${{ github.ref_name }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
